### ISSUE TITLE
Mark Assignment 7 for D Conner

### ISSUE THREAD

**Issue by d-conner** [d-conner/week_07#1]
cd1ebf

**Comment by rharrington31** [comment]
Great job. I really appreciate seeing your logic for testing the functions.

Two adjustments:
* The first function in question 3, which you called `repl_prefix`, does not replace the prefix. Rather, it checks that the specified `prefix` occurs at the beginning of the given `string`.
* For question 4, the modulo operator (`%%`) would have been very helpful!
